with Ada.Strings.Unbounded;
with Format_Utils;
with Text_Utils;
with Ada.Strings.Fixed;
with Ada.Strings;

package body BHPS.Print_Pt1 is
   
   package UK_Format_Utils is new Format_Utils( Float_Type=>Amount, Counter_Type=>Counter_Type );
 
   use Text_Utils;
   use UK_Format_Utils;
   use Ada.Strings.Unbounded;
   use Text_Utils;
   
   INCLUDE_MISSING : constant BOOLEAN := False;
   INDENT : constant String := "   ";

   function Format( v : Sernum_Value ) return String is
      use Ada.Strings.Fixed;
      use Ada.Strings;
   begin
      return Trim( Sernum_Value'Image( v ), Side => Both );
   end Format;

   -- autogenerated starts




   function To_String( a : Egoalt_Rec; num_indents : Natural; loop_count : Natural := 0 ) return String is
      s : Unbounded_String;
   begin
      s := s & (num_indents*INDENT) & " ========== Egoalt";
      if( loop_count > 0 ) then
        s := s & "[ " & Format( loop_count ) & " ] ";
      end if;
      s := s & "=======" & LINE_BREAK;
      if(( a.hid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hid (Household Identification number) [hid] : " & Format(a.hid) & LINE_BREAK;
      end if;
      if(( a.pno /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pno (Ego's Person number) [pno] : " & Format(a.pno) & LINE_BREAK;
      end if;
      if(( a.opno /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "opno (Alter's Person number) [opno] : " & Format(a.opno) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rel )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rel (Relationship of AOPNO to APNO) [rel] : " & Pretty_Print(a.rel) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.sex )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "sex (Sex) [sex] : " & Pretty_Print(a.sex) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.osex )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "osex (Alter's Sex) [osex] : " & Pretty_Print(a.osex) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.nwstat )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "nwstat (Alter's residence at next Wave) [nwstat] : " & Pretty_Print(a.nwstat) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.lwstat )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "lwstat (Alter's residence at last Wave) [lwstat] : " & Pretty_Print(a.lwstat) & LINE_BREAK;
      end if;
      if(( a.pid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pid (Cross-wave person identifier) [pid] : " & Format(a.pid) & LINE_BREAK;
      end if;
      if(( a.opid /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "opid (Alter's Cross-wave person identifier) [opid] : " & Format(a.opid) & LINE_BREAK;
      end if;

      s := s & LINE_BREAK;
      return To_String( s );
   end To_String;
   





   function To_String( a : Hhresp_Rec; num_indents : Natural; loop_count : Natural := 0 ) return String is
      s : Unbounded_String;
   begin
      s := s & (num_indents*INDENT) & " ========== Hhresp";
      if( loop_count > 0 ) then
        s := s & "[ " & Format( loop_count ) & " ] ";
      end if;
      s := s & "=======" & LINE_BREAK;
      if(( a.hid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hid (Household identification number) [hid] : " & Format(a.hid) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhjnd )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhjnd (All persons here since 1.9.90) [hhjnd] : " & Pretty_Print(a.hhjnd) & LINE_BREAK;
      end if;
      if(( a.hhab1y /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhab1y (Date 1st absentee born: year) [hhab1y] : " & Format(a.hhab1y) & LINE_BREAK;
      end if;
      if(( a.hhab2y /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhab2y (Date 2nd absentee born: year) [hhab2y] : " & Format(a.hhab2y) & LINE_BREAK;
      end if;
      if(( a.hhyoi /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhyoi (Year of interview) [hhyoi] : " & Format(a.hhyoi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsivw1 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsivw1 (Whether intervw at address at Wave 1) [hsivw1] : " & Pretty_Print(a.hsivw1) & LINE_BREAK;
      end if;
      if(( a.hhsoih /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhsoih (Hour interview began) [hhsoih] : " & Format(a.hhsoih) & LINE_BREAK;
      end if;
      if(( a.nhhrsp /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nhhrsp (No. interviewed in h/hold (incl proxies)) [nhhrsp] : " & Format(a.nhhrsp) & LINE_BREAK;
      end if;
      if(( a.hhsoim /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhsoim (Minute interview began) [hhsoim] : " & Format(a.hhsoim) & LINE_BREAK;
      end if;
      if(( a.hhdoi /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhdoi (Day of interview) [hhdoi] : " & Format(a.hhdoi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsrins )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsrins (Institutional accommodation rented) [hsrins] : " & Pretty_Print(a.hsrins) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhmoi )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhmoi (Month of interview) [hhmoi] : " & Pretty_Print(a.hhmoi) & LINE_BREAK;
      end if;
      if(( a.hsroom /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsroom (Number of rooms in accommodation) [hsroom] : " & Format(a.hsroom) & LINE_BREAK;
      end if;
      if(( a.hsbeds /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsbeds (Number of bedrooms in accommodation) [hsbeds] : " & Format(a.hsbeds) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsownd )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsownd (House owned or rented) [hsownd] : " & Pretty_Print(a.hsownd) & LINE_BREAK;
      end if;
      if(( a.hsowr1 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsowr1 (PNO of 1st person owning accommodation) [hsowr1] : " & Format(a.hsowr1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsowrp )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsowrp (Outright home owner before 1.9.1991) [hsowrp] : " & Pretty_Print(a.hsowrp) & LINE_BREAK;
      end if;
      if(( a.hsowr2 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsowr2 (PNO of 2nd person owning accommodation) [hsowr2] : " & Format(a.hsowr2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mghave )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mghave (Home mortgaged or owned outright) [mghave] : " & Pretty_Print(a.mghave) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgynot )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgynot (How home came to be owned outright) [mgynot] : " & Pretty_Print(a.mgynot) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hssnip )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hssnip (Sitting tenant when bought) [hssnip] : " & Pretty_Print(a.hssnip) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgly )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgly (Mortgage on home before 1.9.92) [mgly] : " & Pretty_Print(a.mgly) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgstat )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgstat (Mortgage status Sept. 1st 1991) [mgstat] : " & Pretty_Print(a.mgstat) & LINE_BREAK;
      end if;
      if(( a.hsivw6 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw6 (HH interview this address last year) [hsivw6] : " & Format(a.hsivw6) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsvndr )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsvndr (Vendor of home bought as sitting tenant) [hsvndr] : " & Pretty_Print(a.hsvndr) & LINE_BREAK;
      end if;
      if(( a.hsivw5 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw5 (HH interview this address last year) [hsivw5] : " & Format(a.hsivw5) & LINE_BREAK;
      end if;
      if(( a.hsivw4 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw4 (HH interview this address last year) [hsivw4] : " & Format(a.hsivw4) & LINE_BREAK;
      end if;
      if(( a.hsivw2 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw2 (HH interview this address last year) [hsivw2] : " & Format(a.hsivw2) & LINE_BREAK;
      end if;
      if(( a.hsivw3 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw3 (HH interview this address last year) [hsivw3] : " & Format(a.hsivw3) & LINE_BREAK;
      end if;
      if(( a.hscost /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hscost (Original purchase price of property) [hscost] : " & Format(a.hscost) & LINE_BREAK;
      end if;
      if(( a.mgyr0 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "mgyr0 (Year mortgage began) [mgyr0] : " & Format(a.mgyr0) & LINE_BREAK;
      end if;
      if(( a.hsivw8 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw8 (HH interview this address last year) [hsivw8] : " & Format(a.hsivw8) & LINE_BREAK;
      end if;
      if(( a.hsivw9 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw9 (HH interview this address last year) [hsivw9] : " & Format(a.hsivw9) & LINE_BREAK;
      end if;
      if(( a.hsivw7 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivw7 (HH interview this address last year) [hsivw7] : " & Format(a.hsivw7) & LINE_BREAK;
      end if;
      if(( a.hsyr0 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsyr0 (Year became owner: home bought outright) [hsyr0] : " & Format(a.hsyr0) & LINE_BREAK;
      end if;
      if(( a.mgold /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "mgold (Amount borrowed at purchase: mortgagee) [mgold] : " & Format(a.mgold) & LINE_BREAK;
      end if;
      if(( a.hsivlw /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsivlw (HH interview this address last year) [hsivlw] : " & Format(a.hsivlw) & LINE_BREAK;
      end if;
      if(( a.mglife /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "mglife (Years left to pay: mortgagee) [mglife] : " & Format(a.mglife) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgtype )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgtype (Type of mortgage) [mgtype] : " & Pretty_Print(a.mgtype) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgxtra )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgxtra (Taken out additional mortgage on home) [mgxtra] : " & Pretty_Print(a.mgxtra) & LINE_BREAK;
      end if;
      if(( a.mgnew /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "mgnew (Amount of additional mortgage on home) [mgnew] : " & Format(a.mgnew) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgxty1 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgxty1 (Extra loan for home extension) [mgxty1] : " & Pretty_Print(a.mgxty1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgxty2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgxty2 (Extra loan for home improvements) [mgxty2] : " & Pretty_Print(a.mgxty2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgxty3 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgxty3 (Extra loan for car purchase) [mgxty3] : " & Pretty_Print(a.mgxty3) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgxty4 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgxty4 (Extra loan for other consumer goods) [mgxty4] : " & Pretty_Print(a.mgxty4) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.mgxty5 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "mgxty5 (Extra loan for other specified reason) [mgxty5] : " & Pretty_Print(a.mgxty5) & LINE_BREAK;
      end if;
      if(( a.xpmg /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpmg (Last total monthly mortgage payment) [xpmg] : " & Format(a.xpmg) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xpmg1 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xpmg1 (Mortgage includes protection policy) [xpmg1] : " & Pretty_Print(a.xpmg1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xpmg2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xpmg2 (Mortgage includes structure insurance) [xpmg2] : " & Pretty_Print(a.xpmg2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xpmg3 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xpmg3 (Mortgage includes contents insurance) [xpmg3] : " & Pretty_Print(a.xpmg3) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xpmg4 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xpmg4 (Mortgage includes extra payments) [xpmg4] : " & Pretty_Print(a.xpmg4) & LINE_BREAK;
      end if;
      if(( a.hsval /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsval (Value of property: home owners) [hsval] : " & Format(a.hsval) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsjb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsjb (Accommodation with present job: renter) [hsjb] : " & Pretty_Print(a.hsjb) & LINE_BREAK;
      end if;
      if(( a.rentp1 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "rentp1 (Who rents accommodation: 1st mention) [rentp1] : " & Format(a.rentp1) & LINE_BREAK;
      end if;
      if(( a.rentp2 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "rentp2 (Who rents accommodation: 2nd mention) [rentp2] : " & Format(a.rentp2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rentll )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rentll (Landlord of rented accommodation) [rentll] : " & Pretty_Print(a.rentll) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rentf )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rentf (Accommodation rented furnished or other) [rentf] : " & Pretty_Print(a.rentf) & LINE_BREAK;
      end if;
      if(( a.rent /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "rent (Net amount of last rent payment) [rent] : " & Format(a.rent) & LINE_BREAK;
      end if;
      if(( a.rentw /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "rentw (Weeks covered by last rent payment) [rentw] : " & Format(a.rentw) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent1 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent1 (Rent includes water charges) [rent1] : " & Pretty_Print(a.rent1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent2 (Rent includes land or business premises) [rent2] : " & Pretty_Print(a.rent2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent3 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent3 (Rent includes garage) [rent3] : " & Pretty_Print(a.rent3) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent4 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent4 (Rent includes heating lighting or water) [rent4] : " & Pretty_Print(a.rent4) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent5 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent5 (Rent includes meals) [rent5] : " & Pretty_Print(a.rent5) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent7 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent7 (Rent includes sewerage charges) [rent7] : " & Pretty_Print(a.rent7) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent6 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent6 (Rent includes other services) [rent6] : " & Pretty_Print(a.rent6) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.rent8 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "rent8 (Rent includes council tax) [rent8] : " & Pretty_Print(a.rent8) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.renthb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "renthb (Receives rent rebate or rent allowance) [renthb] : " & Pretty_Print(a.renthb) & LINE_BREAK;
      end if;
      if(( a.rentg /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "rentg (Gross rent including Housing Benefit) [rentg] : " & Format(a.rentg) & LINE_BREAK;
      end if;
      if(( a.rentgw /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "rentgw (Weeks covered by gross rent) [rentgw] : " & Format(a.rentgw) & LINE_BREAK;
      end if;
      if(( a.xphsdf /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xphsdf (Problems paying for housing over year) [xphsdf] : " & Format(a.xphsdf) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xphsd1 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xphsd1 (Housing payments required borrowing) [xphsd1] : " & Pretty_Print(a.xphsd1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xphsd2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xphsd2 (Housing payments required cutbacks) [xphsd2] : " & Pretty_Print(a.xphsd2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cdhave )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cdhave (Has one of listed items in accommodation) [cdhave] : " & Pretty_Print(a.cdhave) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hs2ownd )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hs2ownd (Household member owns other property) [hs2ownd] : " & Pretty_Print(a.hs2ownd) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xphsdb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xphsdb (Been 2+ months late with housing payment) [xphsdb] : " & Pretty_Print(a.xphsdb) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprba )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprba (Problems with home: condensation) [hsprba] : " & Pretty_Print(a.hsprba) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hs2val )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hs2val (Value of 2nd property) [hs2val] : " & Pretty_Print(a.hs2val) & LINE_BREAK;
      end if;
      if(( a.mgtot /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "mgtot (Total mortgage on all property) [mgtot] : " & Format(a.mgtot) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbb (Problems with home: damp) [hsprbb] : " & Pretty_Print(a.hsprbb) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hskch )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hskch (Accom: has separate kitchen) [hskch] : " & Pretty_Print(a.hskch) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbc (Problems with home: keeping it warm) [hsprbc] : " & Pretty_Print(a.hsprbc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbd )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbd (Problems with home: leaking roof) [hsprbd] : " & Pretty_Print(a.hsprbd) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cdbght )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cdbght (Bought any consumer durable since 1.9.92) [cdbght] : " & Pretty_Print(a.cdbght) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hskchs )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hskchs (Accom: is separate kitchen shared) [hskchs] : " & Pretty_Print(a.hskchs) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbe )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbe (Problems with home: rot in wood) [hsprbe] : " & Pretty_Print(a.hsprbe) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsbth )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsbth (Accom: has separate bathroom) [hsbth] : " & Pretty_Print(a.hsbth) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsbths )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsbths (Accom: is separate bathroom shared) [hsbths] : " & Pretty_Print(a.hsbths) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbf )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbf (Problems with home: not enough space) [hsprbf] : " & Pretty_Print(a.hsprbf) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd1use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd1use (Colour TV in accommodation) [cd1use] : " & Pretty_Print(a.cd1use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hstlt )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hstlt (Accom: has indoor toilet) [hstlt] : " & Pretty_Print(a.hstlt) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd1own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd1own (Colour TV owned by household member) [cd1own] : " & Pretty_Print(a.cd1own) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hstlts )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hstlts (Accom: is indoor toilet shared) [hstlts] : " & Pretty_Print(a.hstlts) & LINE_BREAK;
      end if;
      if(( a.cd1new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd1new (Colour TV bought in last year) [cd1new] : " & Format(a.cd1new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsgdn )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsgdn (Accom: has terrace/garden) [hsgdn] : " & Pretty_Print(a.hsgdn) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd2use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd2use (VCR in accommodation) [cd2use] : " & Pretty_Print(a.cd2use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsgdns )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsgdns (Accom: is terrace/garden shared) [hsgdns] : " & Pretty_Print(a.hsgdns) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd2own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd2own (VCR owned by household member) [cd2own] : " & Pretty_Print(a.cd2own) & LINE_BREAK;
      end if;
      if(( a.xpgasy /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpgasy (Amount spent on gas since Sept 1996) [xpgasy] : " & Format(a.xpgasy) & LINE_BREAK;
      end if;
      if(( a.cd2new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd2new (VCR bought in last year) [cd2new] : " & Format(a.cd2new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbg )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbg (Accom: shortage of space) [hsprbg] : " & Pretty_Print(a.hsprbg) & LINE_BREAK;
      end if;
      if(( a.xplecy /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xplecy (Amount on electricity since Sept 1996) [xplecy] : " & Format(a.xplecy) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd3use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd3use (Freezer in accommodation) [cd3use] : " & Pretty_Print(a.cd3use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbh )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbh (Accom: noise from neighbours) [hsprbh] : " & Pretty_Print(a.hsprbh) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd3own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd3own (Freezer owned by household member) [cd3own] : " & Pretty_Print(a.cd3own) & LINE_BREAK;
      end if;
      if(( a.cd3new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd3new (Freezer bought in last year) [cd3new] : " & Format(a.cd3new) & LINE_BREAK;
      end if;
      if(( a.xpsfly /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpsfly (Amount on coal/other since Sept 1996) [xpsfly] : " & Format(a.xpsfly) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbi )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbi (Accom: street noise) [hsprbi] : " & Pretty_Print(a.hsprbi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbj )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbj (Accom: not enough light) [hsprbj] : " & Pretty_Print(a.hsprbj) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd4use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd4use (Washing machine in accommodation) [cd4use] : " & Pretty_Print(a.cd4use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd4own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd4own (Washing machine owned by h/hold member) [cd4own] : " & Pretty_Print(a.cd4own) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbk )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbk (Accom: lack of adequate heating) [hsprbk] : " & Pretty_Print(a.hsprbk) & LINE_BREAK;
      end if;
      if(( a.cdnuxp /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cdnuxp (Amount spent on items in past year) [cdnuxp] : " & Format(a.cdnuxp) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbl )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbl (Accom: condensation) [hsprbl] : " & Pretty_Print(a.hsprbl) & LINE_BREAK;
      end if;
      if(( a.cd4new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd4new (Washing machine bought in last year) [cd4new] : " & Format(a.cd4new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.gfuela )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "gfuela (Installed solar panels for electricity) [gfuela] : " & Pretty_Print(a.gfuela) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd5use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd5use (Tumble dryer in accommodation) [cd5use] : " & Pretty_Print(a.cd5use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.gfuelb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "gfuelb (Installed solar water heating) [gfuelb] : " & Pretty_Print(a.gfuelb) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbm )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbm (Accom: leaky roof) [hsprbm] : " & Pretty_Print(a.hsprbm) & LINE_BREAK;
      end if;
      if(( a.hsip /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsip (Paid for home improvements in past year) [hsip] : " & Format(a.hsip) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd5own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd5own (Tumble dryer owned by h/hold member) [cd5own] : " & Pretty_Print(a.cd5own) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.gfuelc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "gfuelc (Installed wind turbine for electricity) [gfuelc] : " & Pretty_Print(a.gfuelc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbn )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbn (Accom: damp walls, floors etc) [hsprbn] : " & Pretty_Print(a.hsprbn) & LINE_BREAK;
      end if;
      if(( a.hsipxp /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsipxp (Amount paid for home improvements) [hsipxp] : " & Format(a.hsipxp) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.gelec )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "gelec (HH buys electricity on Green Tariff) [gelec] : " & Pretty_Print(a.gelec) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbo )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbo (Accom: rot in windows, floors) [hsprbo] : " & Pretty_Print(a.hsprbo) & LINE_BREAK;
      end if;
      if(( a.cd5new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd5new (Tumble dryer bought in last year) [cd5new] : " & Format(a.cd5new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbp )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbp (Accom: pollution/environmental problems) [hsprbp] : " & Pretty_Print(a.hsprbp) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd6use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd6use (Dish washer in accommodation) [cd6use] : " & Pretty_Print(a.cd6use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.larcyc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "larcyc (Local Authority runs recycling scheme) [larcyc] : " & Pretty_Print(a.larcyc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd6own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd6own (Dish washer owned by h/hold member) [cd6own] : " & Pretty_Print(a.cd6own) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhrcyc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhrcyc (Separates HH rubbish for collection) [hhrcyc] : " & Pretty_Print(a.hhrcyc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsprbq )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsprbq (Accom: vandalism or crime) [hsprbq] : " & Pretty_Print(a.hsprbq) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhbb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhbb (HH uses bottle bank or other facilities) [hhbb] : " & Pretty_Print(a.hhbb) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsctax )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsctax (Council tax band of accommodation) [hsctax] : " & Pretty_Print(a.hsctax) & LINE_BREAK;
      end if;
      if(( a.cd6new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd6new (Dish washer bought in last year) [cd6new] : " & Format(a.cd6new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd7use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd7use (Microwave oven in accommodation) [cd7use] : " & Pretty_Print(a.cd7use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd7own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd7own (Microwave oven owned by h/hold member) [cd7own] : " & Pretty_Print(a.cd7own) & LINE_BREAK;
      end if;
      if(( a.cd7new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd7new (Microwave oven bought in last year) [cd7new] : " & Format(a.cd7new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd8use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd8use (Home computer in accommodation) [cd8use] : " & Pretty_Print(a.cd8use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd8own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd8own (Home computer owned by h/hold member) [cd8own] : " & Pretty_Print(a.cd8own) & LINE_BREAK;
      end if;
      if(( a.cd8new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd8new (Home computer bought in last year) [cd8new] : " & Format(a.cd8new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd9use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd9use (CD player in accommodation) [cd9use] : " & Pretty_Print(a.cd9use) & LINE_BREAK;
      end if;
      if(( a.hs2valo /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hs2valo (Value of other property) [hs2valo] : " & Format(a.hs2valo) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd9own )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd9own (CD player owned by household member) [cd9own] : " & Pretty_Print(a.cd9own) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hs2vala )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hs2vala (Oth property: amt 50,000 or more) [hs2vala] : " & Pretty_Print(a.hs2vala) & LINE_BREAK;
      end if;
      if(( a.cd9new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd9new (CD player bought in last year) [cd9new] : " & Format(a.cd9new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hs2valb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hs2valb (Oth property: amt 100,000 or more) [hs2valb] : " & Pretty_Print(a.hs2valb) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hs2valc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hs2valc (Oth property: amt 250,000 or more) [hs2valc] : " & Pretty_Print(a.hs2valc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.heatch )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "heatch (Household has central heating) [heatch] : " & Pretty_Print(a.heatch) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hs2vald )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hs2vald (Oth property: amt 10,000 or more) [hs2vald] : " & Pretty_Print(a.hs2vald) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.heatyp )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "heatyp (Central heating fuel type) [heatyp] : " & Pretty_Print(a.heatyp) & LINE_BREAK;
      end if;
      if(( a.cd1cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd1cst (Cost of Colour TV bought in last year) [cd1cst] : " & Format(a.cd1cst) & LINE_BREAK;
      end if;
      if(( a.xpoily /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpoily (Expenditure on fuel oil in last year) [xpoily] : " & Format(a.xpoily) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.gasuse )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "gasuse (HH has gas supply, not gas cent htg) [gasuse] : " & Pretty_Print(a.gasuse) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.gasway )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "gasway (Method of paying for gas) [gasway] : " & Pretty_Print(a.gasway) & LINE_BREAK;
      end if;
      if(( a.cd2cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd2cst (Cost of VCR bought in past year) [cd2cst] : " & Format(a.cd2cst) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivfho )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivfho (Final household interview outcome) [ivfho] : " & Pretty_Print(a.ivfho) & LINE_BREAK;
      end if;
      if(( a.xpgasl /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpgasl (Amount of last gas payment) [xpgasl] : " & Format(a.xpgasl) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.carown )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "carown (Household member owns vehicle) [carown] : " & Pretty_Print(a.carown) & LINE_BREAK;
      end if;
      if(( a.xhwght /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwght (Household Weight) [xhwght] : " & Format(a.xhwght) & LINE_BREAK;
      end if;
      if(( a.xpgasw /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpgasw (Weeks covered by last gas payment) [xpgasw] : " & Format(a.xpgasw) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xpbldf )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xpbldf (Problems paying household bills) [xpbldf] : " & Pretty_Print(a.xpbldf) & LINE_BREAK;
      end if;
      if(( a.cd3cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd3cst (Cost of freezer bought in last year) [cd3cst] : " & Format(a.cd3cst) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xphp )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xphp (Repayments on hire purchase or loans) [xphp] : " & Pretty_Print(a.xphp) & LINE_BREAK;
      end if;
      if(( a.xpgaslw /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpgaslw (Expenditure on gas last week) [xpgaslw] : " & Format(a.xpgaslw) & LINE_BREAK;
      end if;
      if(( a.carval /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "carval (Value vehicle(s) less amount outstanding) [carval] : " & Format(a.carval) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd10use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd10use (Satellite Dish in accommodation) [cd10use] : " & Pretty_Print(a.cd10use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.lecway )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "lecway (Method of paying for electricity) [lecway] : " & Pretty_Print(a.lecway) & LINE_BREAK;
      end if;
      if(( a.cd10new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd10new (Satellite Dish bought in last year) [cd10new] : " & Format(a.cd10new) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xphpdf )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xphpdf (Repayments a burden on household) [xphpdf] : " & Pretty_Print(a.xphpdf) & LINE_BREAK;
      end if;
      if(( a.xplecl /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xplecl (Amount of last electricity payment) [xplecl] : " & Format(a.xplecl) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd11use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd11use (Cable TV in accommodation) [cd11use] : " & Pretty_Print(a.cd11use) & LINE_BREAK;
      end if;
      if(( a.cd4cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd4cst (Cost of wash machine bought in last year) [cd4cst] : " & Format(a.cd4cst) & LINE_BREAK;
      end if;
      if(( a.xplecw /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xplecw (Weeks covered by electricity payment) [xplecw] : " & Format(a.xplecw) & LINE_BREAK;
      end if;
      if(( a.cd11new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd11new (Cable TV bought in last year) [cd11new] : " & Format(a.cd11new) & LINE_BREAK;
      end if;
      if(( a.xpleclw /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpleclw (Expenditure on electricity last week) [xpleclw] : " & Format(a.xpleclw) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd12use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd12use (Telephone in accommodation) [cd12use] : " & Pretty_Print(a.cd12use) & LINE_BREAK;
      end if;
      if(( a.cd12new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd12new (Telephone bought in last year) [cd12new] : " & Format(a.cd12new) & LINE_BREAK;
      end if;
      if(( a.xpfood /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpfood (Total weekly food and grocery bill) [xpfood] : " & Format(a.xpfood) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ncars )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ncars (Car or van available for private use) [ncars] : " & Pretty_Print(a.ncars) & LINE_BREAK;
      end if;
      if(( a.cd5cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd5cst (Cost of tumble dryer bought in last year) [cd5cst] : " & Format(a.cd5cst) & LINE_BREAK;
      end if;
      if(( a.ivh1 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivh1 (PNO of 1st person answering HH questions) [ivh1] : " & Format(a.ivh1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hspc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hspc (IC: Household has home computer) [hspc] : " & Pretty_Print(a.hspc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hswpc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hswpc (Type of computer in household) [hswpc] : " & Pretty_Print(a.hswpc) & LINE_BREAK;
      end if;
      if(( a.ivh2 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivh2 (PNO of 2nd person answering HH questions) [ivh2] : " & Format(a.ivh2) & LINE_BREAK;
      end if;
      if(( a.ivh3 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivh3 (PNO of 3rd person answering HH questions) [ivh3] : " & Format(a.ivh3) & LINE_BREAK;
      end if;
      if(( a.cd6cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd6cst (Cost of dish washer bought in last year) [cd6cst] : " & Format(a.cd6cst) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcwhen )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcwhen (When was computer acquired) [pcwhen] : " & Pretty_Print(a.pcwhen) & LINE_BREAK;
      end if;
      if(( a.ivhc1 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivhc1 (PNO of 1st person answering HH Comp Form) [ivhc1] : " & Format(a.ivhc1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcmodm )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcmodm (Does computer have fax/modem) [pcmodm] : " & Pretty_Print(a.pcmodm) & LINE_BREAK;
      end if;
      if(( a.ivhc2 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivhc2 (PNO of 2nd person answering HH Comp Form) [ivhc2] : " & Format(a.ivhc2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcnet )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcnet (Is computer connected to the internet) [pcnet] : " & Pretty_Print(a.pcnet) & LINE_BREAK;
      end if;
      if(( a.ivhc3 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivhc3 (PNO of 3rd person answering HH Comp Form) [ivhc3] : " & Format(a.ivhc3) & LINE_BREAK;
      end if;
      if(( a.pcusr1 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pcusr1 (Computer user : 1st mentioned) [pcusr1] : " & Format(a.pcusr1) & LINE_BREAK;
      end if;
      if(( a.cd7cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd7cst (Cost of microwave bought in last year) [cd7cst] : " & Format(a.cd7cst) & LINE_BREAK;
      end if;
      if(( a.pcusr2 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pcusr2 (Computer user : 2nd mentioned) [pcusr2] : " & Format(a.pcusr2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhdc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhdc (Household level document check) [hhdc] : " & Pretty_Print(a.hhdc) & LINE_BREAK;
      end if;
      if(( a.hhwght /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhwght (Household Weight) [hhwght] : " & Format(a.hhwght) & LINE_BREAK;
      end if;
      if(( a.pcusr3 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pcusr3 (Computer user : 3rd mentioned) [pcusr3] : " & Format(a.pcusr3) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hstype )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hstype (Type of accommodation) [hstype] : " & Pretty_Print(a.hstype) & LINE_BREAK;
      end if;
      if(( a.cd8cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd8cst (Cost of computer bought in last year) [cd8cst] : " & Format(a.cd8cst) & LINE_BREAK;
      end if;
      if(( a.pcusr4 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pcusr4 (Computer user : 4th mentioned) [pcusr4] : " & Format(a.pcusr4) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsfloor )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsfloor (Floor of main living accommodation) [hsfloor] : " & Pretty_Print(a.hsfloor) & LINE_BREAK;
      end if;
      if(( a.pcusr5 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pcusr5 (Computer user : 5th mentioned) [pcusr5] : " & Format(a.pcusr5) & LINE_BREAK;
      end if;
      if(( a.pcusr6 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pcusr6 (Computer user : 6th mentioned) [pcusr6] : " & Format(a.pcusr6) & LINE_BREAK;
      end if;
      if(( a.hhsize /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhsize (Number of Persons in Household) [hhsize] : " & Format(a.hhsize) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuse1 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuse1 (Computer use : paid work) [pcuse1] : " & Pretty_Print(a.pcuse1) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhtype )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhtype (Household Type) [hhtype] : " & Pretty_Print(a.hhtype) & LINE_BREAK;
      end if;
      if(( a.cd9cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd9cst (Cost of CD player bought in last year) [cd9cst] : " & Format(a.cd9cst) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuse2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuse2 (Computer use: voluntary work) [pcuse2] : " & Pretty_Print(a.pcuse2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.region )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "region (Region / Metropolitan Area) [region] : " & Pretty_Print(a.region) & LINE_BREAK;
      end if;
      if(( a.nch02 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nch02 (Number children in household aged 0-2) [nch02] : " & Format(a.nch02) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuse3 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuse3 (Computer use : educational work) [pcuse3] : " & Pretty_Print(a.pcuse3) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuse4 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuse4 (Computer use : playing games) [pcuse4] : " & Pretty_Print(a.pcuse4) & LINE_BREAK;
      end if;
      if(( a.cd10cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd10cst (Cost of satellite bought in last year) [cd10cst] : " & Format(a.cd10cst) & LINE_BREAK;
      end if;
      if(( a.nch34 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nch34 (Number children in household aged 3-4) [nch34] : " & Format(a.nch34) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuse5 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuse5 (Computer use : word processing) [pcuse5] : " & Pretty_Print(a.pcuse5) & LINE_BREAK;
      end if;
      if(( a.nch511 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nch511 (Number children in household aged 5-11) [nch511] : " & Format(a.nch511) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuse6 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuse6 (Computer use : financial accounts) [pcuse6] : " & Pretty_Print(a.pcuse6) & LINE_BREAK;
      end if;
      if(( a.nch1215 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nch1215 (Number children in household aged 12-15) [nch1215] : " & Format(a.nch1215) & LINE_BREAK;
      end if;
      if(( a.nch1618 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nch1618 (Number dependent children in HH 16+) [nch1618] : " & Format(a.nch1618) & LINE_BREAK;
      end if;
      if(( a.cd11cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd11cst (Cost of cable TV bought in last year) [cd11cst] : " & Format(a.cd11cst) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuse7 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuse7 (Computer use : other) [pcuse7] : " & Pretty_Print(a.pcuse7) & LINE_BREAK;
      end if;
      if(( a.nkids /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nkids (Number of children in household) [nkids] : " & Format(a.nkids) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.pcuses )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "pcuses (Computer user : frequency) [pcuses] : " & Pretty_Print(a.pcuses) & LINE_BREAK;
      end if;
      if(( a.nwed /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nwed (Number of married persons in household) [nwed] : " & Format(a.nwed) & LINE_BREAK;
      end if;
      if(( a.npens /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "npens (Number over pensionable age in household) [npens] : " & Format(a.npens) & LINE_BREAK;
      end if;
      if(( a.cd12cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd12cst (Cost of telephone bought in last year) [cd12cst] : " & Format(a.cd12cst) & LINE_BREAK;
      end if;
      if(( a.na75pl /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "na75pl (Number aged 75 and over in household) [na75pl] : " & Format(a.na75pl) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscana )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscana (Keep home adequately warm) [hscana] : " & Pretty_Print(a.hscana) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscnta )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscnta (Would like to keep home warm) [hscnta] : " & Pretty_Print(a.hscnta) & LINE_BREAK;
      end if;
      if(( a.agechy /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "agechy (Age of youngest child in household) [agechy] : " & Format(a.agechy) & LINE_BREAK;
      end if;
      if(( a.ncouple /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ncouple (Number of Couples in household) [ncouple] : " & Format(a.ncouple) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscanb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscanb (Pay for annual holiday) [hscanb] : " & Pretty_Print(a.hscanb) & LINE_BREAK;
      end if;
      if(( a.nonepar /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nonepar (Number of Single Parents in household) [nonepar] : " & Format(a.nonepar) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscntb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscntb (Would like to pay for annual holiday) [hscntb] : " & Pretty_Print(a.hscntb) & LINE_BREAK;
      end if;
      if(( a.nemp /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nemp (Number in Employment in household) [nemp] : " & Format(a.nemp) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscanc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscanc (Replace furniture) [hscanc] : " & Pretty_Print(a.hscanc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscntc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscntc (Would like to replace furniture) [hscntc] : " & Pretty_Print(a.hscntc) & LINE_BREAK;
      end if;
      if(( a.nue /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nue (Number Unemployed in household) [nue] : " & Format(a.nue) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscand )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscand (Buy new clothes) [hscand] : " & Pretty_Print(a.hscand) & LINE_BREAK;
      end if;
      if(( a.nwage /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nwage (Number in household of working age) [nwage] : " & Format(a.nwage) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.cd13use )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "cd13use (MOBILE phone in accommodation) [cd13use] : " & Pretty_Print(a.cd13use) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.tenure )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "tenure (Housing tenure) [tenure] : " & Pretty_Print(a.tenure) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscntd )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscntd (Would like to buy new clothes) [hscntd] : " & Pretty_Print(a.hscntd) & LINE_BREAK;
      end if;
      if(( a.cd13new /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd13new (MOBILE phone bought in last year) [cd13new] : " & Format(a.cd13new) & LINE_BREAK;
      end if;
      if(( a.cd13cst /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "cd13cst (Cost of MOBILE phone bought in past year) [cd13cst] : " & Format(a.cd13cst) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscane )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscane (Eat meat on alternate days) [hscane] : " & Pretty_Print(a.hscane) & LINE_BREAK;
      end if;
      if(( a.xphsn /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xphsn (Net monthly housing costs) [xphsn] : " & Format(a.xphsn) & LINE_BREAK;
      end if;
      if(( a.xphsg /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xphsg (Gross monthly housing costs) [xphsg] : " & Format(a.xphsg) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscnte )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscnte (Would like meat on alternate days) [hscnte] : " & Pretty_Print(a.hscnte) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsnet1 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsnet1 (Access to internet - home computer) [hsnet1] : " & Pretty_Print(a.hsnet1) & LINE_BREAK;
      end if;
      if(( a.xpoil /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpoil (Monthly expenditure on oil) [xpoil] : " & Format(a.xpoil) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscanf )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscanf (Feed visitors once a month) [hscanf] : " & Pretty_Print(a.hscanf) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsnet2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsnet2 (Access to internet - digital tv) [hsnet2] : " & Pretty_Print(a.hsnet2) & LINE_BREAK;
      end if;
      if(( a.xpgas /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpgas (Monthly expenditure on gas) [xpgas] : " & Format(a.xpgas) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscntf )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscntf (Can't afford visitors once a month) [hscntf] : " & Pretty_Print(a.hscntf) & LINE_BREAK;
      end if;
      if(( a.xplec /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xplec (Monthly expenditure on electricity) [xplec] : " & Format(a.xplec) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhmove )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhmove (Mover household indicator) [hhmove] : " & Pretty_Print(a.hhmove) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsnet3 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsnet3 (Access to internet - mobile phone) [hsnet3] : " & Pretty_Print(a.hsnet3) & LINE_BREAK;
      end if;
      if(( a.xpfuel /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpfuel (Monthly expenditure on oil/gas/electric) [xpfuel] : " & Format(a.xpfuel) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsnet4 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsnet4 (Access to internet - other) [hsnet4] : " & Pretty_Print(a.hsnet4) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.phone )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "phone (Household has telephone) [phone] : " & Pretty_Print(a.phone) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsnetb )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsnetb (Broadband connection from home computer) [hsnetb] : " & Pretty_Print(a.hsnetb) & LINE_BREAK;
      end if;
      if(( a.fieqfcb /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fieqfcb (HH Equivalence scale before hsing costs) [fieqfcb] : " & Format(a.fieqfcb) & LINE_BREAK;
      end if;
      if(( a.fieqfca /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fieqfca (HH Equivalence scale after hsing costs) [fieqfca] : " & Format(a.fieqfca) & LINE_BREAK;
      end if;
      if(( a.fihhyr /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhyr (Annual household income (1.9.90-1.9.91)) [fihhyr] : " & Format(a.fihhyr) & LINE_BREAK;
      end if;
      if(( a.fihhmn /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhmn (Household income: month before interview) [fihhmn] : " & Format(a.fihhmn) & LINE_BREAK;
      end if;
      if(( a.fihhml /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhml (HH labour income month before intv) [fihhml] : " & Format(a.fihhml) & LINE_BREAK;
      end if;
      if(( a.fihhmnl /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhmnl (HH non-labour income month before intv) [fihhmnl] : " & Format(a.fihhmnl) & LINE_BREAK;
      end if;
      if(( a.fihhmp /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhmp (HH pension income month before intv) [fihhmp] : " & Format(a.fihhmp) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscanh )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscanh (Two pairs of shoes for each adult) [hscanh] : " & Pretty_Print(a.hscanh) & LINE_BREAK;
      end if;
      if(( a.fihhmb /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhmb (HH benefit income month before intv) [fihhmb] : " & Format(a.fihhmb) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhorig )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhorig (Sample Origin: original BHPS or ECHP) [hhorig] : " & Pretty_Print(a.hhorig) & LINE_BREAK;
      end if;
      if(( a.hhfoih /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhfoih (Hour interview ended) [hhfoih] : " & Format(a.hhfoih) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscnth )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscnth (Would like two pairs of shoes for each) [hscnth] : " & Pretty_Print(a.hscnth) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscank )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscank (Keep house well decorated) [hscank] : " & Pretty_Print(a.hscank) & LINE_BREAK;
      end if;
      if(( a.fihhmt /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhmt (HH transfer income month before intv) [fihhmt] : " & Format(a.fihhmt) & LINE_BREAK;
      end if;
      if(( a.hhfoim /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhfoim (Minute interview ended) [hhfoim] : " & Format(a.hhfoim) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscntk )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscntk (Would like to keep house well decorated) [hscntk] : " & Pretty_Print(a.hscntk) & LINE_BREAK;
      end if;
      if(( a.fihhmi /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhmi (HH investment income month before intv) [fihhmi] : " & Format(a.fihhmi) & LINE_BREAK;
      end if;
      if(( a.fihhyl /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhyl (Annual household labour income) [fihhyl] : " & Format(a.fihhyl) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscanl )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscanl (Have hhold contents insurance) [hscanl] : " & Pretty_Print(a.hscanl) & LINE_BREAK;
      end if;
      if(( a.fihhynl /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhynl (Annual household non-labour income) [fihhynl] : " & Format(a.fihhynl) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hscntl )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hscntl (Would like to have contents insurance) [hscntl] : " & Pretty_Print(a.hscntl) & LINE_BREAK;
      end if;
      if(( a.fihhyp /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhyp (Annual household pension income) [fihhyp] : " & Format(a.fihhyp) & LINE_BREAK;
      end if;
      if(( a.fihhyb /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhyb (Annual household benefit income) [fihhyb] : " & Format(a.fihhyb) & LINE_BREAK;
      end if;
      if(( a.fihhyt /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhyt (Annual household transfer income) [fihhyt] : " & Format(a.fihhyt) & LINE_BREAK;
      end if;
      if(( a.fihhyi /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fihhyi (Annual household investment income) [fihhyi] : " & Format(a.fihhyi) & LINE_BREAK;
      end if;
      if(( a.mgnewi /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "mgnewi (Imputation flag - AMGNEW (base)) [mgnewi] : " & Format(a.mgnewi) & LINE_BREAK;
      end if;
      if(( a.xpmgi /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xpmgi (Imputation flag - AXPMG  (base)) [xpmgi] : " & Format(a.xpmgi) & LINE_BREAK;
      end if;
      if(( a.hhyoi4 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhyoi4 (Year of interview: 4 digit) [hhyoi4] : " & Format(a.hhyoi4) & LINE_BREAK;
      end if;
      if(( a.hsvali /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsvali (Imputation flag - AHSVAL (base)) [hsvali] : " & Format(a.hsvali) & LINE_BREAK;
      end if;
      if(( a.renti /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "renti (Imputation flag - ARENT  (base)) [renti] : " & Format(a.renti) & LINE_BREAK;
      end if;
      if(( a.rentgi /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "rentgi (Imputation flag - ARENTG (base)) [rentgi] : " & Format(a.rentgi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xphsni )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xphsni (Imputation flag - AXPHSN (derived)) [xphsni] : " & Pretty_Print(a.xphsni) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.xphsgi )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "xphsgi (Imputation flag - AXPHSG (derived)) [xphsgi] : " & Pretty_Print(a.xphsgi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhmni )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhmni (Imputation flag - AFIHHMN (derived)) [fihhmni] : " & Pretty_Print(a.fihhmni) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhmli )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhmli (Imputation flag - AFIHHML (derived)) [fihhmli] : " & Pretty_Print(a.fihhmli) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihmnli )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihmnli (Imputation flag - AFIHMNL (derived)) [fihmnli] : " & Pretty_Print(a.fihmnli) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhmpi )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhmpi (Imputation flag - AFIHHMP (derived)) [fihhmpi] : " & Pretty_Print(a.fihhmpi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhmbi )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhmbi (Imputation flag - AFIHHMB (derived)) [fihhmbi] : " & Pretty_Print(a.fihhmbi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhmti )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhmti (Imputation flag - AFIHHMT (derived)) [fihhmti] : " & Pretty_Print(a.fihhmti) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhmii )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhmii (Imputation flag - AFIHHMI (derived)) [fihhmii] : " & Pretty_Print(a.fihhmii) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhyri )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhyri (Imputation flag - AFIHHYR (derived)) [fihhyri] : " & Pretty_Print(a.fihhyri) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhyli )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhyli (Imputation flag - AFIHHYL (derived)) [fihhyli] : " & Pretty_Print(a.fihhyli) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhyni )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhyni (Imputation flag - AFIHHYNL (derived)) [fihhyni] : " & Pretty_Print(a.fihhyni) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhypi )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhypi (Imputation flag - AFIHHYP (derived)) [fihhypi] : " & Pretty_Print(a.fihhypi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhybi )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhybi (Imputation flag - AFIHHYB (derived)) [fihhybi] : " & Pretty_Print(a.fihhybi) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhyti )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhyti (Imputation flag - AFIHHYT (derived)) [fihhyti] : " & Pretty_Print(a.fihhyti) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhyii )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhyii (Imputation flag - AFIHHYI (derived)) [fihhyii] : " & Pretty_Print(a.fihhyii) & LINE_BREAK;
      end if;
      if(( a.mgyr04 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "mgyr04 (Year mortgage began: 4 digit) [mgyr04] : " & Format(a.mgyr04) & LINE_BREAK;
      end if;
      if(( a.hsyr04 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hsyr04 (Year became owner: 4 digit) [hsyr04] : " & Format(a.hsyr04) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.region2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "region2 (Government Office Region) [region2] : " & Pretty_Print(a.region2) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fihhsel )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fihhsel (Flag: S/Emp loss not inc. in HH income) [fihhsel] : " & Pretty_Print(a.fihhsel) & LINE_BREAK;
      end if;
      if(( a.xhwghte /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwghte (ECHP Household weight) [xhwghte] : " & Format(a.xhwghte) & LINE_BREAK;
      end if;
      if(( a.xhwtsw1 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtsw1 (Household weight -inc Scotland/Wales) [xhwtsw1] : " & Format(a.xhwtsw1) & LINE_BREAK;
      end if;
      if(( a.xhwtsw2 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtsw2 (Household weight -only Scotland/Wales) [xhwtsw2] : " & Format(a.xhwtsw2) & LINE_BREAK;
      end if;
      if(( a.xhwtuk1 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtuk1 (Household weight -inc all samples) [xhwtuk1] : " & Format(a.xhwtuk1) & LINE_BREAK;
      end if;
      if(( a.xhwtuk2 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtuk2 (Household weight -within UK estimates) [xhwtuk2] : " & Format(a.xhwtuk2) & LINE_BREAK;
      end if;

      s := s & LINE_BREAK;
      return To_String( s );
   end To_String;
   





   function To_String( a : Hhsamp_Rec; num_indents : Natural; loop_count : Natural := 0 ) return String is
      s : Unbounded_String;
   begin
      s := s & (num_indents*INDENT) & " ========== Hhsamp";
      if( loop_count > 0 ) then
        s := s & "[ " & Format( loop_count ) & " ] ";
      end if;
      s := s & "=======" & LINE_BREAK;
      if(( a.hid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hid (Household identification number) [hid] : " & Format(a.hid) & LINE_BREAK;
      end if;
      if(( a.hhac /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhac (Area code) [hhac] : " & Format(a.hhac) & LINE_BREAK;
      end if;
      if(( a.ivnadd /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivnadd (Household found at new address in field) [ivnadd] : " & Format(a.ivnadd) & LINE_BREAK;
      end if;
      if(( a.hhan /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhan (Address number) [hhan] : " & Format(a.hhan) & LINE_BREAK;
      end if;
      if(( a.hhno /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhno (Household number) [hhno] : " & Format(a.hhno) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivia )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivia (Interviewer area) [ivia] : " & Pretty_Print(a.ivia) & LINE_BREAK;
      end if;
      if(( a.fid /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fid (Fieldwork identification number) [fid] : " & Format(a.fid) & LINE_BREAK;
      end if;
      if(( a.ivid /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivid (Interviewer identification number) [ivid] : " & Format(a.ivid) & LINE_BREAK;
      end if;
      if(( a.ivlnc /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivlnc (Total calls at last known address) [ivlnc] : " & Format(a.ivlnc) & LINE_BREAK;
      end if;
      if(( a.ivtnc /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivtnc (Total calls at interview address) [ivtnc] : " & Format(a.ivtnc) & LINE_BREAK;
      end if;
      if(( a.ivnc /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivnc (Total number of calls) [ivnc] : " & Format(a.ivnc) & LINE_BREAK;
      end if;
      if(( a.nhh /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nhh (Number of households at address) [nhh] : " & Format(a.nhh) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.iviam )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "iviam (Area interview took place-nonlocal mover) [iviam] : " & Pretty_Print(a.iviam) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hstype )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hstype (Type of accommodation) [hstype] : " & Pretty_Print(a.hstype) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.nelocly )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "nelocly (NI unlisted resident) [nelocly] : " & Pretty_Print(a.nelocly) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hsfloor )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hsfloor (Floor of main living accommodation) [hsfloor] : " & Pretty_Print(a.hsfloor) & LINE_BREAK;
      end if;
      if(( a.ivosmrh /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivosmrh (No. OSMs - whole HH refusal to intervwr) [ivosmrh] : " & Format(a.ivosmrh) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivfho )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivfho (Final household interview outcome) [ivfho] : " & Pretty_Print(a.ivfho) & LINE_BREAK;
      end if;
      if(( a.ivnsmrh /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivnsmrh (No. new HH membs - whl HH ref to intvwr) [ivnsmrh] : " & Format(a.ivnsmrh) & LINE_BREAK;
      end if;
      if(( a.ivhsize /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivhsize (Estimated number in refusal household) [ivhsize] : " & Format(a.ivhsize) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhdc )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhdc (Document check - h/hold quest're comp?) [hhdc] : " & Pretty_Print(a.hhdc) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivhzif )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivhzif (Household 0 issued to field) [ivhzif] : " & Pretty_Print(a.ivhzif) & LINE_BREAK;
      end if;
      if(( a.ivnadlt /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivnadlt (Estimated adults in refusal household) [ivnadlt] : " & Format(a.ivnadlt) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivisst )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivisst (Coversheet issue status) [ivisst] : " & Pretty_Print(a.ivisst) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivips )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivips (Inter-penetrating sample indicator) [ivips] : " & Pretty_Print(a.ivips) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivrrefh )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivrrefh (Reason for household refusal) [ivrrefh] : " & Pretty_Print(a.ivrrefh) & LINE_BREAK;
      end if;
      if(( a.xhwght /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwght (Household Weight) [xhwght] : " & Format(a.xhwght) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivconv )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivconv (Refusal conversion attempted) [ivconv] : " & Pretty_Print(a.ivconv) & LINE_BREAK;
      end if;
      if(( a.ivrage /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ivrage (Estimated age of person refusing HH int) [ivrage] : " & Format(a.ivrage) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivrsex )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivrsex (Sex of person refusing HH interview) [ivrsex] : " & Pretty_Print(a.ivrsex) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivreis )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivreis (Re-issued to field) [ivreis] : " & Pretty_Print(a.ivreis) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhmove )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhmove (Mover household indicator) [hhmove] : " & Pretty_Print(a.hhmove) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivovt )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivovt (Original voucher type) [ivovt] : " & Pretty_Print(a.ivovt) & LINE_BREAK;
      end if;
      if(( a.hhwght /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hhwght (Household Weight) [hhwght] : " & Format(a.hhwght) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.hhorig )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "hhorig (Sample Origin: original BHPS or ECHP) [hhorig] : " & Pretty_Print(a.hhorig) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.region )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "region (Region / Metropolitan Area) [region] : " & Pretty_Print(a.region) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ivavt )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ivavt (Actual voucher type) [ivavt] : " & Pretty_Print(a.ivavt) & LINE_BREAK;
      end if;
      if(( a.ahid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "ahid (Household identification number - Wave 1) [ahid] : " & Format(a.ahid) & LINE_BREAK;
      end if;
      if(( a.strata /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "strata (Stratification class) [strata] : " & Format(a.strata) & LINE_BREAK;
      end if;
      if(( a.gechphid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "gechphid (ECHP Household ID) [gechphid] : " & Format(a.gechphid) & LINE_BREAK;
      end if;
      if(( a.psu /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "psu (Primary Sampling Unit) [psu] : " & Format(a.psu) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.region2 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "region2 (Government Office Region) [region2] : " & Pretty_Print(a.region2) & LINE_BREAK;
      end if;
      if(( a.xhwghte /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwghte (ECHP Household weight) [xhwghte] : " & Format(a.xhwghte) & LINE_BREAK;
      end if;
      if(( a.xhwtuk1 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtuk1 (Household weight -inc all samples) [xhwtuk1] : " & Format(a.xhwtuk1) & LINE_BREAK;
      end if;
      if(( a.xhwtsw1 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtsw1 (Household weight -inc Scotland/Wales) [xhwtsw1] : " & Format(a.xhwtsw1) & LINE_BREAK;
      end if;
      if(( a.xhwtuk2 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtuk2 (Household weight -within UK estimates) [xhwtuk2] : " & Format(a.xhwtuk2) & LINE_BREAK;
      end if;
      if(( a.xhwtsw2 /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "xhwtsw2 (Household weight -only Scotland/Wales) [xhwtsw2] : " & Format(a.xhwtsw2) & LINE_BREAK;
      end if;

      s := s & LINE_BREAK;
      return To_String( s );
   end To_String;
   





   function To_String( a : Income_Rec; num_indents : Natural; loop_count : Natural := 0 ) return String is
      s : Unbounded_String;
   begin
      s := s & (num_indents*INDENT) & " ========== Income";
      if( loop_count > 0 ) then
        s := s & "[ " & Format( loop_count ) & " ] ";
      end if;
      s := s & "=======" & LINE_BREAK;
      if(( a.hid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "hid (Household identification number) [hid] : " & Format(a.hid) & LINE_BREAK;
      end if;
      if(( a.pno /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pno (Person number) [pno] : " & Format(a.pno) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.ficode )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "ficode (Income receipt code) [ficode] : " & Pretty_Print(a.ficode) & LINE_BREAK;
      end if;
      if(( a.nfr /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "nfr (Number of income receipts totalled here) [nfr] : " & Format(a.nfr) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frall )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frall (Received payment each month) [frall] : " & Pretty_Print(a.frall) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr01 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr01 (Payment received in September 1990) [fr01] : " & Pretty_Print(a.fr01) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr02 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr02 (Payment received in October 1990) [fr02] : " & Pretty_Print(a.fr02) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr03 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr03 (Payment received in November 1990) [fr03] : " & Pretty_Print(a.fr03) & LINE_BREAK;
      end if;
      if(( a.fr04 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fr04 (Payment received in December 1990) [fr04] : " & Format(a.fr04) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr05 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr05 (Payment received in January 1991) [fr05] : " & Pretty_Print(a.fr05) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr06 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr06 (Payment received in February 1991) [fr06] : " & Pretty_Print(a.fr06) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr07 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr07 (Payment received in March 1991) [fr07] : " & Pretty_Print(a.fr07) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr08 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr08 (Payment received in April 1991) [fr08] : " & Pretty_Print(a.fr08) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr09 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr09 (Payment received in May 1991) [fr09] : " & Pretty_Print(a.fr09) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr10 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr10 (Payment received in June 1991) [fr10] : " & Pretty_Print(a.fr10) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr11 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr11 (Payment received in July 1991) [fr11] : " & Pretty_Print(a.fr11) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr12 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr12 (Payment received in August 1991) [fr12] : " & Pretty_Print(a.fr12) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr13 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr13 (Payment received in September 1991) [fr13] : " & Pretty_Print(a.fr13) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr14 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr14 (Payment received in October 1991) [fr14] : " & Pretty_Print(a.fr14) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr15 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr15 (Payment received in November 1991) [fr15] : " & Pretty_Print(a.fr15) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr17 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr17 (Payment received in January 1993) [fr17] : " & Pretty_Print(a.fr17) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr16 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr16 (Payment received in December 1991) [fr16] : " & Pretty_Print(a.fr16) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr18 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr18 (Payment received in February 2000) [fr18] : " & Pretty_Print(a.fr18) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frnow )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frnow (Is still receiving payment) [frnow] : " & Pretty_Print(a.frnow) & LINE_BREAK;
      end if;
      if(( a.frval /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "frval (Last amount received) [frval] : " & Format(a.frval) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr19 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr19 (Payment received in March 2000) [fr19] : " & Pretty_Print(a.fr19) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fr20 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fr20 (Payment received in April 2000) [fr20] : " & Pretty_Print(a.fr20) & LINE_BREAK;
      end if;
      if(( a.frw /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "frw (Weeks covered by last amount received) [frw] : " & Format(a.frw) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frjt )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frjt (Last payment: sole or joint recipient) [frjt] : " & Pretty_Print(a.frjt) & LINE_BREAK;
      end if;
      if(( a.frjtpn /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "frjtpn (PNO of joint recipient) [frjtpn] : " & Format(a.frjtpn) & LINE_BREAK;
      end if;
      if(( a.fiseq /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fiseq (Income receipt sequence number) [fiseq] : " & Format(a.fiseq) & LINE_BREAK;
      end if;
      if(( a.fim09l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim09l (Estimated Income in September 1990) [fim09l] : " & Format(a.fim09l) & LINE_BREAK;
      end if;
      if(( a.fim10l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim10l (Estimated Income in October 1990) [fim10l] : " & Format(a.fim10l) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.fradd )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "fradd (Rcvd ben/payment addtnl prompt reqired) [fradd] : " & Pretty_Print(a.fradd) & LINE_BREAK;
      end if;
      if(( a.fim11l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim11l (Estimated Income in November 1990) [fim11l] : " & Format(a.fim11l) & LINE_BREAK;
      end if;
      if(( a.fim12l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim12l (Estimated Income in December 1990) [fim12l] : " & Format(a.fim12l) & LINE_BREAK;
      end if;
      if(( a.fim01t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim01t (Estimated Income in January 1991) [fim01t] : " & Format(a.fim01t) & LINE_BREAK;
      end if;
      if(( a.fim02t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim02t (Estimated Income in February 1991) [fim02t] : " & Format(a.fim02t) & LINE_BREAK;
      end if;
      if(( a.fim03t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim03t (Estimated Income in March 1991) [fim03t] : " & Format(a.fim03t) & LINE_BREAK;
      end if;
      if(( a.fim04t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim04t (Estimated Income in April 1991) [fim04t] : " & Format(a.fim04t) & LINE_BREAK;
      end if;
      if(( a.fim05t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim05t (Estimated Income in May 1991) [fim05t] : " & Format(a.fim05t) & LINE_BREAK;
      end if;
      if(( a.fim06t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim06t (Estimated Income in June 1991) [fim06t] : " & Format(a.fim06t) & LINE_BREAK;
      end if;
      if(( a.fim07t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim07t (Estimated Income in July 1991) [fim07t] : " & Format(a.fim07t) & LINE_BREAK;
      end if;
      if(( a.fim08t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim08t (Estimated Income in August 1991) [fim08t] : " & Format(a.fim08t) & LINE_BREAK;
      end if;
      if(( a.fim09t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim09t (Estimated Income in September 1991) [fim09t] : " & Format(a.fim09t) & LINE_BREAK;
      end if;
      if(( a.fim10t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim10t (Estimated Income in October 1991) [fim10t] : " & Format(a.fim10t) & LINE_BREAK;
      end if;
      if(( a.fim11t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim11t (Estimated Income in November 1991) [fim11t] : " & Format(a.fim11t) & LINE_BREAK;
      end if;
      if(( a.fim12t /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim12t (Estimated Income in December 1991) [fim12t] : " & Format(a.fim12t) & LINE_BREAK;
      end if;
      if(( a.frvali /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "frvali (Imputation flag - AFRVAL (base)) [frvali] : " & Format(a.frvali) & LINE_BREAK;
      end if;
      if(( a.pid /= MISSING_SERNUM) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "pid (Cross-wave person identifier) [pid] : " & Format(a.pid) & LINE_BREAK;
      end if;
      if(( a.fim01n /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim01n (Estimated Income in January 1993) [fim01n] : " & Format(a.fim01n) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frjtvf )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frjtvf (Joint receipt verification flag) [frjtvf] : " & Pretty_Print(a.frjtvf) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frec01 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frec01 (Payment received in January 1996) [frec01] : " & Pretty_Print(a.frec01) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frec02 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frec02 (Payment received in February 1996) [frec02] : " & Pretty_Print(a.frec02) & LINE_BREAK;
      end if;
      if(( a.fim02n /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim02n (Estimated Income in February 2000) [fim02n] : " & Format(a.fim02n) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frec03 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frec03 (Payment received in March 1996) [frec03] : " & Pretty_Print(a.frec03) & LINE_BREAK;
      end if;
      if(( a.fim03n /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim03n (Estimated Income in March 2000) [fim03n] : " & Format(a.fim03n) & LINE_BREAK;
      end if;
      if(( a.frec04 /= MISS) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "frec04 (Payment received in April 1996) [frec04] : " & Format(a.frec04) & LINE_BREAK;
      end if;
      if(( a.fim04n /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim04n (Estimated Income in April 2000) [fim04n] : " & Format(a.fim04n) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frec05 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frec05 (Payment received in May 1996) [frec05] : " & Pretty_Print(a.frec05) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frec06 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frec06 (Payment received in June 1996) [frec06] : " & Pretty_Print(a.frec06) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frec07 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frec07 (Payment received in July 1996) [frec07] : " & Pretty_Print(a.frec07) & LINE_BREAK;
      end if;
      if(( not Null_Or_Missing( a.frec08 )) or INCLUDE_MISSING )then
         s := s & (num_indents*INDENT) & "frec08 (Payment received in August 1996) [frec08] : " & Pretty_Print(a.frec08) & LINE_BREAK;
      end if;
      if(( a.fim01l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim01l (Estimated Income in January 1996) [fim01l] : " & Format(a.fim01l) & LINE_BREAK;
      end if;
      if(( a.fim02l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim02l (Estimated Income in February 1996) [fim02l] : " & Format(a.fim02l) & LINE_BREAK;
      end if;
      if(( a.fim03l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim03l (Estimated Income in March 1996) [fim03l] : " & Format(a.fim03l) & LINE_BREAK;
      end if;
      if(( a.fim04l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim04l (Estimated Income in April 1996) [fim04l] : " & Format(a.fim04l) & LINE_BREAK;
      end if;
      if(( a.fim05l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim05l (Estimated Income in May 1996) [fim05l] : " & Format(a.fim05l) & LINE_BREAK;
      end if;
      if(( a.fim06l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim06l (Estimated Income in June 1996) [fim06l] : " & Format(a.fim06l) & LINE_BREAK;
      end if;
      if(( a.fim07l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim07l (Estimated Income in July 1996) [fim07l] : " & Format(a.fim07l) & LINE_BREAK;
      end if;
      if(( a.fim08l /= MISS_R) or INCLUDE_MISSING ) then
         s := s & (num_indents*INDENT) & "fim08l (Estimated Income in August 1996) [fim08l] : " & Format(a.fim08l) & LINE_BREAK;
      end if;

      s := s & LINE_BREAK;
      return To_String( s );
   end To_String;
   



   -- autogenerated ends   
   
end BHPS.Print_Pt1;

