package ZM.Raw is

   type Rec_Type is new String( 1 .. 2 );

   type Person_Count is new Integer range 0 .. 31;
   subtype Person_Range is Person_Count range 1 .. 31;

   type Person_Rec is record
       s : String( 1 .. 1 );
    end record;
   
   type Person_Array is array( Person_Range ) of Person_Rec;
   
   type Household is record
      hid                    : Sernum_Value;
      num_people             : Person_Count := 0;
      person                 : Person_Array;
      
   end record;
   
   type Sec00A is record
      RECTYPE : Integer;
      hid : Sernum_Value;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      chief : Integer;
      HHstatus : Integer;
      Reason : Integer;
      Sample : Integer;
      responde : Integer;
      persons : Integer;
      Srvdate : Integer;
      Day : Integer;
      Month : Integer;
      Year : Integer;
   end record;

   type Sec01A is record
      RECTYPE : Integer;
      hid : Sernum_Value;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      PID : Integer;
      s1q3a : Integer;
      s1q3b : Integer;
      s1q4 : Integer;
      s1q5 : Integer;
      s1q6 : Integer;
      s1q7a : Integer;
      s1q7b : Integer;
      s1q7c : Integer;
      s1q8 : Integer;
      s1q9 : Integer;
      s1q10 : Integer;
      s1q11 : Integer;
   end  record;

   type Sec02A is record
      RECTYPE : Integer;
      hid : Sernum_Value;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      PID : Integer;
      s1q3a : Integer;
      s1q3b : Integer;
      s1q4 : Integer;
      s1q5 : Integer;
      s1q6 : Integer;
      s1q7a : Integer;
      s1q7b : Integer;
      s1q7c : Integer;
      s1q8 : Integer;
      s1q9 : Integer;
      s1q10 : Integer;
      s1q11 : Integer;
      WEIGHT : Amount;
      years : Integer;
      HHsize : Integer;
      q : Integer;
      p : Integer;
      r : Integer;
      stratrum : Integer;
      s2q1 : Integer;
      s2q2 : Integer;
      s2q3 : Integer;
   end record;
   
   type Sec03A is record
      rectype : Integer;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      PID : Integer;
      S3Q1 : Integer;
      S3Q2 : Integer;
      S3Q3 : Integer;
      S3Q4 : Integer;
      S3Q5 : Integer;
      S3Q6 : Integer;
      S3Q7 : Integer;
      S3Q8 : Integer;
      S3Q9 : Integer;
      S3Q10 : Integer;
      S3Q11 : Integer;
      S3Q12 : Integer;
      S3Q13 : Integer;
      S3Q14 : Integer;
      S3Q15 : Integer;
      S3Q16 : Integer;
      S3Q17 : Integer;
      hid : Sernum_Value;
   end record;

   type Sec04A is record
      rectype : Integer;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      PID : Integer;
      S4Q1 : Integer;
      S4Q2 : Integer;
      S4Q3 : Integer;
      S4Q4 : Integer;
      S4Q5 : Integer;
      S4Q6 : Integer;
      S4Q7 : Integer;
      S4Q8 : Integer;
      S4Q9 : Integer;
      S4Q10 : Integer;
      hid : Sernum_Value;
   end record;

   type Sec07A is record
      rectype : Integer;
      hid : Sernum_Value;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      asset : Integer;
      s7q1 : Integer;
      s7q2 : Integer;
      s7q3 : Integer;
      s7q4 : Amount;
      s7q5 : Amount;
   end record;

   type Sec08a is record
      rectype : Integer;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      S8Q1 : Integer;
      S8Q2 : Integer;
      S8Q3 : Integer;
      S8Q4 : Integer;
      S8Q5A : Integer;
      S8Q5B : Integer;
      S8Q5C : Integer;
      S8Q5D : Integer;
      S8Q5E : Integer;
      S8Q6A : Integer;
      S8Q6B : Integer;
      S8Q6C : Integer;
      S8Q7A : Integer;
      S8Q7B : Integer;
      S8Q8A : Integer;
      S8Q8B : Integer;
      S8Q9A : Integer;
      S8Q9B : Integer;
      S8Q10 : Integer;
      S8Q11 : Integer;
      S8Q12 : Integer;
      S8Q13 : Integer;
      S8Q14 : Integer;
      S8Q15 : Integer;
      S8Q16 : Integer;
      S8Q17 : Integer;
      hid : Sernum_Value;
      WEIGHT : Amount;
   end record;
   
   type Sec09a is record
      rectype : Integer;
      hid : Sernum_Value;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      Facility : Integer;
      Nearest : Integer;
      Distance : Integer;
      Usage : Integer;
      Means : Integer;
      How_long : Integer;
      Reason : Integer;
   end record;
   
   type Se11AA is record
      RECTYPE : Integer;
      province : Integer;
      district : Integer;
      Const : Integer;
      ward : Integer;
      Csa : Integer;
      Sea : Integer;
      Rururb : Integer;
      Stratum : Integer;
      hhnumber : Integer;
      S11Q1 : Integer;
      S11Q2a : Integer;
      S11Q3a1 : Integer;
      S11Q3a2 : Integer;
      S11Q4a : Integer;
      S11Q5a : Integer;
      S11Q6a : Integer;
      S11Q2b : Integer;
      S11Q3b1 : Integer;
      S11Q3b2 : Integer;
      S11Q4b : Integer;
      S11Q5b : Integer;
      S11Q6b : Integer;
      S11Q2c : Integer;
      S11Q3c1 : Integer;
      S11Q3c2 : Integer;
      S11Q4c : Integer;
      S11Q5c : Integer;
      S11Q6c : Integer;
      S11Q2d : Integer;
      S11Q3d1 : Integer;
      S11Q3d2 : Integer;
      S11Q4d : Integer;
      S11Q5d : Integer;
      S11Q6d : Integer;
      S11Q2e : Integer;
      S11Q3e1 : Integer;
      S11Q3e2 : Integer;
      S11Q4e : Integer;
      S11Q5e : Integer;
      S11Q6e : Integer;
      S11Q2f : Integer;
      S11Q3f1 : Integer;
      S11Q3f2 : Integer;
      S11Q4f : Integer;
      S11Q5f : Integer;
      S11Q6f : Integer;
      S11Q2g : Integer;
      S11Q3g1 : Integer;
      S11Q3g2 : Integer;
      S11Q4g : Integer;
      S11Q5g : Integer;
      S11Q6g : Integer;
      S11Q2h : Integer;
      S11Q3h1 : Integer;
      S11Q3h2 : Integer;
      S11Q4h : Integer;
      S11Q5h : Integer;
      S11Q6h : Integer;
      S11Q2i : Integer;
      S11Q3i1 : Integer;
      S11Q3i2 : Integer;
      S11Q4i : Integer;
      S11Q5i : Integer;
      S11Q6i : Integer;
      S11Q2j : Integer;
      S11Q3j1 : Integer;
      S11Q3j2 : Integer;
      S11Q4j : Integer;
      S11Q5j : Integer;
      S11Q6j : Integer;
      S11Q2k : Integer;
      S11Q3k1 : Integer;
      S11Q3k2 : Integer;
      S11Q4k : Integer;
      S11Q5k : Integer;
      S11Q6k : Integer;
      S11Q7l : Integer;
      S11Q8la : Integer;
      S11Q8lb : Integer;
      S11Q8lc : Integer;
      S11Q7m : Integer;
      S11Q8ma : Integer;
      S11Q8mb : Integer;
      S11Q8mc : Integer;
      S11Q7n : Integer;
      S11Q8na : Integer;
      S11Q8nb : Integer;
      S11Q8nc : Integer;
      S11Q7o : Integer;
      S11Q8oa : Integer;
      S11Q8ob : Integer;
      S11Q8oc : Integer;
      S11Q7p : Integer;
      S11Q8pa : Integer;
      S11Q8pb : Integer;
      S11Q8pc : Integer;
      S11Q9A1 : Integer;
      S11Q9A2 : Integer;
      S11Q9B1 : Integer;
      S11Q9B2 : Integer;
      S11Q9C1 : Integer;
      S11Q9C2 : Integer;
      S11Q9D1 : Integer;
      S11Q9D2 : Integer;
      S11Q10A1 : Integer;
      S11Q10A2 : Integer;
      S11Q10B1 : Integer;
      S11Q10B2 : Integer;
      S11Q10C1 : Integer;
      S11Q10C2 : Integer;
      S11Q10D1 : Integer;
      S11Q10D2 : Integer;
      S11Q11 : Integer;
      S11Q111 : Integer;
      S11Q112 : Integer;
      S11Q113 : Integer;
      hid : Sernum_Value;
   end record;

end ZM.Raw;
